syntax = "proto3";

package ttm.services.accommodation.v3;

import "google/protobuf/timestamp.proto";
import "ttm/services/accommodation/v3/property_types.proto";
import "ttm/types/v1/common.proto";
import "ttm/types/v1/language.proto";
import "ttm/types/v2/product_code.proto";

message AccommodationProductInfoRequest {
  // Message header
  ttm.types.v1.RequestHeader header = 1;

  // Only respond with the products that are modified after this timestamp
  //
  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp modified_after = 2;

  // Languages
  repeated ttm.types.v1.Language languages = 3;

  // Property codes
  repeated ttm.types.v2.SupplierProductCode supplier_codes = 4;
}

message AccommodationProductInfoResponse {
  // Message header
  ttm.types.v1.ResponseHeader header = 1;

  // Product list: Properties
  repeated ttm.services.accommodation.v3.PropertyExtendedInfo properties = 2;
}

// Accommodation product info service definition
//
/// @custom:ttm-service type:product routing:p2p on-chain:false
service AccommodationProductInfoService {
  // Returns product list for accommodation (properties)
  rpc AccommodationProductInfo(AccommodationProductInfoRequest) returns (AccommodationProductInfoResponse);
}
